<a href="https://colab.research.google.com/github/yusnivtr/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.7949, 0.3143, 0.8345, 0.6456, 0.8297, 0.0653, 0.2219],
        [0.7124, 0.2280, 0.9073, 0.5643, 0.1525, 0.4605, 0.8174],
        [0.7472, 0.7787, 0.4512, 0.8236, 0.8893, 0.1266, 0.5039],
        [0.2264, 0.4311, 0.4038, 0.3139, 0.0443, 0.8709, 0.1391],
        [0.1059, 0.3901, 0.7443, 0.0923, 0.3263, 0.7736, 0.0325],
        [0.1643, 0.4670, 0.6298, 0.0688, 0.4213, 0.7361, 0.3655],
        [0.8333, 0.5178, 0.5932, 0.7848, 0.9277, 0.7370, 0.1333]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor1,tensor2.T)

tensor([[2.4002],
        [2.6519],
        [2.5035],
        [1.5775],
        [1.4669],
        [1.5489],
        [2.8291]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor1,tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [26]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")

# Create two random tensors on GPU
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)
tensor1, tensor2


Device : cuda


(tensor([[0.7572, 0.6948, 0.5209],
         [0.5932, 0.8797, 0.6286]], device='cuda:0'),
 tensor([[0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
%%time
result_tensor = torch.matmul(tensor1,tensor2.T)
result_tensor

CPU times: user 319 µs, sys: 0 ns, total: 319 µs
Wall time: 325 µs


tensor([[0.8795, 1.3148],
        [0.4493, 0.7189]], device='cuda:0')

In [15]:
%%time
tensor1 @ tensor2.T

CPU times: user 222 µs, sys: 11 µs, total: 233 µs
Wall time: 238 µs


tensor([[0.8795, 1.3148],
        [0.4493, 0.7189]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max & min
torch.max(result_tensor), torch.min(result_tensor)

(tensor(1.3148, device='cuda:0'), tensor(0.4493, device='cuda:0'))

In [20]:
torch.max(result_tensor,dim=1), torch.min(result_tensor,dim=1)

(torch.return_types.max(
 values=tensor([1.3148, 0.7189], device='cuda:0'),
 indices=tensor([1, 1], device='cuda:0')),
 torch.return_types.min(
 values=tensor([0.8795, 0.4493], device='cuda:0'),
 indices=tensor([0, 0], device='cuda:0')))

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max, arg min
torch.argmax(result_tensor), torch.argmin(result_tensor)

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
new_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(f"Original tensor: {tensor}")
print(f"Original tensor's shape {tensor.shape}")
print(f"New tensor: {new_tensor}")
print(f"New tensor's shape {new_tensor.shape}")


Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original tensor's shape torch.Size([1, 1, 1, 10])
New tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New tensor's shape torch.Size([10])
